---

ansible_python_interperter: /usr/bin/python3

host_version: os-ubuntu-2004

admin_user: gridadmin

# conf01 : One grid server, one asset server, one region server
config_version: "01"

# database

db_backup_node: "os-backup"

# Network

os_public_port: 8002
os_private_port: 8003

# login service
WelcomeMessage: "Welcome, Spirit!!!"

# gridinfo service
gridname: "Ansible Generated Test Grid"
gridnick: "AnsibleTest"
admin_group: opensim
public_key: ~/.ssh/id_rsa.pub


# gridmode is hypergrid of grid
gridmode: "grid"

# enable/disbale remote administration of regions. Credentials should be set
# in the similator vault
remote_admin_access: false


# Voice , user credentials should be in ~/.vars/opensim/vivox.yml
#         Format of vivox.yml
#         ---
#         vivox_server: www.osp.vivox.com
#         vivox_sip_uri: osp.vivox.com
#         vivox_admin_user: "vivox-user"
#         vivox_admin_password: "vivox-password"
#
#         To obtain a username and password send an email to opensim@vivox.com

vivox: true
