---
  host_version: os-ubuntu-1804

  # conf01 : One grid server, one asset server, one region server
  config_version: os-conf01

# login service
  WelcomeMessage: "Welcome, Spirit!!!"

# gridinfo service
  gridname: "My Own Ansible Generated Test Grid"
  gridnick: "AnsibleTest"

  admin_group: opensim
  public_key: ~/.ssh/id_rsa.pub
