---
# tasks file for robust
- name: Copy Robust.ini file from template into opensim/bin directory.
  template:
    src: Robust.ini.j2
    dest: "/home/{{ admin_user}}/{{ conf_dir }}/Robust.ini"
    owner: {{ admin_user}}
    group: root
    mode: 0644
    tags: [ 'deploy' ]
