---
# tasks file for db-backup

- name: install backup script
  template:
    src: opensim-backup.sh.j2
    dest: /usr/bin/opensim-backup.sh
    owner: "{{ admin_user }}"
    group: "{{ admin_group }}"
    mode: '0754'

- name: Schedule database backups
  cron:
    name: "schedule daily opensim database backups"
    job: "/usr/bin/opensim-backup.sh"
    weekday: "*"
    hour: "{{ backup_hours}}"
    minute: "{{ backup_minute }}"
    user: "{{ admin_user }}"
