---
- hosts: localhost
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: set the docker user
      set_fact:
        docker_user: 
          - "{{ lookup('env', 'USER') }}"
      become: no
      tags: ['identity', 'configure']

  roles:
    - control
    - geerlingguy.docker
