---
- hosts: os-region00
  become: yes
  gather_facts: no

  vars:
    sftp_user: gridfiles
    sftp_password: "{{ vault_sftp_password }}"
    sftp_group: "{{ admin_group }}"
    sftp_folder: "/var/sftp"
    sftp_uploads: "{{ sftp_folder }}/uploads"

    users:
      - username:  "{{ sftp_user }}"
        password: "{{ sftp_password }}"
        update_password: always
        groups: ['{{ sftp_group }}']
        home: "/home/{{ sftp_user }}"

  roles:
      # configure system account for sftp user who will uplaod iar/oar files
    - singleplatform-eng.users

    - sftp-user
