---
# KaiShunWorldz grid conf01 files
# Date : July 20, 2018

- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

- include: control.yml
- include: baseline.yml
- include: opensim.yml
- include: storage.yml
- include: db-backup.yml
- include: grid.yml
- include: asset.yml
- include: simulator.yml
