---
# KaiShunWorldz grid conf01 files
# Date : July 20, 2018

- hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

# configure localhost as Ansible Orchestrator Host
# include: orchestrator.yml

# configure the robust nodes and the simulator nodes
- include: simulator.yml

# configure default simulator node to be able to receive uploads with sftp
- include file-transfer.yml

# configure opensim nodes with a storage provider
- include: db-storage.yml

# confige opensim nodes to schedule backups
- include: db-backup.yml
