---
# KaiShunWorldz grid conf01 files
# Date : July 20, 2018

- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: update apt update_cache
      apt: update_cache=yes cache_valid_time=86400

- include: control.yml
- include: baseline.yml
- include: opensim.yml
- include: storage.yml
- include: percona-xtrabackup.yml
- include: grid.yml
- include: asset.yml
- include: simulator.yml
