---
# Database storage is provided by mysql on each opensim server
- hosts: opensim
  become: yes
  gather_facts: yes
  vars:
    mysql_config_include_files:
      - src: authentication.cnf
    mysql_databases:
      - name: "{{ db_name }}"
        collation: utf8_general_ci
        encoding: utf8
        state: present

    mysql_users:
      - name: "{{ db_user }}"
        host: localhost
        password: "{{ db_password }}"
        priv: "*.*:ALL"

  pre_tasks:
    - name: Set discovered Ansible Python interpreter.
      set_fact:
        ansible_python_interpreter: "{{ ansible_facts.python.executable }}"
      when: ansible_python_interpreter is not defined

  roles:
    - geerlingguy.mysql
     - percona
