---
- name: install helper tools
  apt: 
    name: ['curl', 'tree', 'screen', 'git', 'vsftpd', 'python3-pip', 'libssl-dev']
    state: present
  notify: restart vsftpd
  tags: ['packages']

- name: update apt cache for pip3
  apt: update_cache=yes

- name: install testing tools
  block:
    - name: install lint tools
      pip:
        name: ['yamllint', 'setuptools', 'ansible-lint', 'molecule', 'docker-py']
        state: present
        executable: /usr/bin/pip3
  
    - name: install docker requirements
      apt: 
        name: ['apt-transport-https', 'ca-certificates', 'gnupg-agent', 'software-properties-common']
        state: present

    - name: add the docker key ring
      shell: \
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      register: keyring_result

    - name: assert docker key ring has been received
      assert: 
        that:
          - keyring_result.stdout.find('OK') != -1
        fail_msg: "Unable to download docker key ring."

    - name: verify key ring
      command: 'apt-key fingerprint 0EBFCD88'
      become: yes
      register: key_ring_verification

    - name: assert the docker key ring is valid
      assert:
        that:
          key_ring_verification.stdout.find('docker') != -1
        fail_msg: "Failed to add a valid docker key ring."

    - name: add docker repository
      command: \
        sudo add-apt-repository "deb [arch={{ os_architecture }}] https://download.docker.com/{{ os_system }}/{{ os_distro }} {{ docker_distro }} stable"
      register: docker_cli


    - name: update apt cache for docker
      apt: update_cache=yes

    - name: install docker ce
      apt: 
        name: ['docker-ce', 'docker-ce-cli', 'containerd']
        state: present
    

    - name: check if docker installed
      stat: path=/usr/bin/docker
      register: docker_installed

  tags: ['packages']
