---
# tasks file for sftp-user

# There must be a sftp root folder owned by root
- name: check sftp root folder
  stat: path="{{ sftp_folder }}"
  register: sftp_folder_present

- name: create sftp root folder
  file:
    path: "{{ sftp_folder }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not sftp_folder_present.stat.exists

# Create the user upload folder
- name: check upload folder is present
  stat: path="{{ sftp_folder}}/{{ sftp_user }}"
  register: sftp_upload_folder_present

- name: create sftp upload folder
  file:
    path: "{{ sftp_folder }}/{{ sftp_user }}"
    state: directory
    owner: "{{ sftp_user }}"
    group: "{{ sftp_group }}"
    mode: 0755
  when: not sftp_upload_folder_present.stat.exists

# Allow the ftp user to upload files but no ssh login
- name: config sftp user
  blockinfile:
    path: "/etc/ssh/sshd_config"
    marker: "# Ansible inserted sftp user"
    insertafter: EOF
    backup: yes
    block: |
      PasswordAuthentication yes
      Match User {{ sftp_user }}
      ForceCommand internal-sftp
      ChrootDirectory {{ sftp_folder }}
      PermitTunnel no
      AllowAgentForwarding no
      AllowTcpForwarding no
      X11Forwarding no
  notify: restart sshd
  when: not sftp_upload_folder_present.stat.exists
