---
#- name: install mysql
#  apt: name=mysql-server state=present
#  tags: [ 'packages' ]

#- name: ensure mysql listening only to local host
#  notify: restart mysql
#  tags: [ 'authorize','configure' ]

#- name: Install pip
#  apt: name=python3-pip state=present
#  tags: [ 'packages' ]

#- name: install the python mysql package
#  pip: name=pymysql state=present
#
#- name: Remove anonymous database users
#  mysql_user: name='' host_all=yes state=absent
#  tags: [ 'configure' ]

- name: Create the opensim databases
  mysql_db: name="{{db_name}}" state=present
  tags: [ 'configure' ]

- name: Create the database admin users
  mysql_user: name="{{db_user}}" password="{{db_password}}"  state=present
  tags: [ 'configure' ]

- name: grant privileges when connected from other hosts
  mysql_user: name="{{db_user}}" priv='{{db_name}}.*:ALL' host="{{item}}" host_all=yes
  tags: [ 'authorize','configure']
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
