- name: Configure full database backups
  cron:
    name: "Stream Full Databse Backup"
    cron_file: "/etc/crontab"
    job: "sudo xtrabackup --backup --compressed --stream=xbstream /tmp | nc os-backup {{ backup_port }}"
    weekday: "0"
    hour: "1"
    minute: "12"
    user: "{{ admin_user }}"
  when: not ansible_nodename  == 'os-backup'

- name: Store Full Backups on the backup system
  cron: "Setup Full Dabase Reception"
    name: "Receive Full Backups"
    job: "sudo nc -l 9999 | sudo xbstream -xv -C /var/backups/os-asset"
    weekday: "0"
    hour: "1"
    minute: "12"
    user: "ansible"
  when: ansible_nodename == 'os-backup'
