galaxy_info:
  author: KaiShunOleander
  description: configure sftp user for uplaoding files
  company: KaiShunWorldz


  license: license (BSD-3-Clause, GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial
        - trusty
    - name: Debian
      versions:
        - buster
        - stretch
        - jessie

  galaxy_tags:
    - opensim
    - opensimuator

dependencies: []
