# setup the grid servicses with teh correcy hostnames

- name: configure the asset service
  ini_file:
    path: "/home/{{ admin_user}}/{{ conf_dir}}/OpenSim.ini"
    section: Const
    option: AssetHostName
    value: '"127.0.0.1"'
  changed_when: no
  tags: [ 'os_services', 'simulator', 'configure']

- name: confige the Xinventory service
  ini_file:
    path: "/home/{{ admin_user}}/{{ conf_dir}}/OpenSim.ini"
    section: Const
    option: InventoryHostName
    value: '"{{ item }}"'
  with_items:
    - "{{ groups['asset_services'] }}"
  changed_when: no
  tags: [ 'os_services', 'simulator', 'configure']

- name: confige the grid service
  ini_file:
    path: "/home/{{ admin_user}}/{{ conf_dir}}/OpenSim.ini"
    section: Const
    option: GridHostName
    value: '"{{ item }}"'
  with_items:
    - "{{ groups['grid_services'] }}"
  changed_when: no
  tags: [ 'os_services', 'simulator', 'configure']
