

  - name: configure storage provider (login info)
    ini_file:
      path: '{{ storage_provider }}'
      section: Const
      option: DB_Name
      value: '"{{ db_name}}"'
    changed_when: no
    tags: [ 'database_service','configure'  ]

  - name: configure storage provider (user info)
    ini_file:
      path: '{{ storage_provider }}'
      section: Const
      option: DB_User
      value: '"{{ db_user }}"'
    changed_when: no
    tags: [ 'database_service','configure'  ]

  - name: configure storage provider ( password info)
    ini_file:
      path: '{{ storage_provider }}'
      section: Const
      option: DB_Password
      value: '"{{ vault_db_password }}"'
    changed_when: no
    tags: [ 'database_service','configure'  ]
