---
# tasks file for opensim
  - name: create opensim admin group
    group: name="{{ admin_group }}" state=present
    tags: [ 'identify','configure'  ]

  - name: create system users for opensim administration
    user: name="{{ admin_user }}" group="{{ admin_group }}" shell=/bin/bash
      update_password=always state=present
    tags: [ 'identity','configure'  ]

  - name: add gridadmin to sudoers
    lineinfile:
      path: "/etc/sudoers"
      state: present
      regexp: '^{{ admin_user}}'
      line: '{{ admin_user}} ALL=(ALL) NOPASSWD:ALL'
    tags: [ 'authorize','configure' ]

  - name: add ssh keys for remote access by this control system
    authorized_key: user="{{ admin_user }}" key="{{ lookup('file', public_key) }}"
    tags: [ 'authenticate','configure'  ]

  - name: git clone opensim binaries
    become: yes
    become_user: "{{ admin_user }}"
    git:
      repo: "{{git_bin}}"
      dest: "/home/{{ admin_user }}/{{ host_version }}"
      version: master
      force: yes
      accept_hostkey: yes
      key_file: "/home/{{ admin_user }}/.ssh/id_rsa"
    tags: [ 'deploy' ]

  - name: git clone opensim configuration files
    become: yes
    become_user: "{{ admin_user }}"
    git:
      repo: "{{git_cnf}}"
      dest: "/home/{{ admin_user }}/os-config"
      version: master
      force: yes
      accept_hostkey: yes
      key_file: "/home/{{ admin_user }}/.ssh/id_rsa"
    tags: [ 'deploy' ]

  - name: unlink existing default configuration folder
    file: path="/home/{{ admin_user }}/{{ conf_dir }}" state=absent
    changed_when: no
    tags: [ 'deploy' ]

  - name: activate configuration folder
    become: yes
    become_user: "{{ admin_user }}"
    file:
      src: "/home/{{ admin_user }}/os-config/{{ config_version }}"
      dest: "/home/{{ admin_user }}/{{ conf_dir }}"
      state: link
    changed_when: no
    tags: [ 'deploy' ]

  - name: unlink existing default opensim binaries
    file: path="/home/{{ admin_user}}/opensim" state=absent
    changed_when: no
    tags: [ 'deploy' ]

  - name: link to opensim binaries
    become: yes
    become_user: "{{ admin_user}} "
    file:
      src: "/home/{{ admin_user}}/{{ host_version }}"
      dest: "/home/{{ admin_user }}/opensim"
      state: link
    changed_when: no
    tags: [ 'deploy' ]

  - name: add opensim bin folder to path
    lineinfile:
      path: "/home/{{ admin_user}}/.bashrc"
      state: present
      regexp: 'export PATH=\$PATH:\$HOME\/opensim\/bin'
      line: 'export PATH=$PATH:$HOME/opensim/bin'
    changed_when: no
    tags: [ 'deploy' ]


  - name: configure storage provider (login info)
    ini_file:
      path: '{{ storage_provider }}'
      section: Const
      option: DB_Name
      value: '"{{ db_name}}"'
    changed_when: no
    tags: [ 'DatabaseService','configure'  ]

  - name: configure storage provider (user info)
    ini_file:
      path: '{{ storage_provider }}'
      section: Const
      option: DB_User
      value: '"{{ db_user }}"'
    changed_when: no
    tags: [ 'DatabaseService','configure'  ]

  - name: configure storage provider ( password info)
    ini_file:
      path: '{{ storage_provider }}'
      section: Const
      option: DB_Password
      value: '"{{ vault_db_password }}"'
    changed_when: no
    tags: [ 'DatabaseService','configure'  ]
