---
# tasks file for opensim

# create the system accounts, greate the opensim group and set sudoers
# duplicate the public key of controler to remotes
- include: system_accounts.yml

# get the opensim binaries and the opensim config ini files
- include: setup_opensim_bin.yml
  when: not ansible_nodename in groups['backup']

# configure data storage provider in openmsimulator ini files
# - include: data_storage_provider.yml
