---
# tasks file for asset_services
  - name: configure path to storage provider
    ini_file:
      path: '{{ asset_config }}'
      section: DatabaseService
      option: Include-Storage
      value: '"{{ storage_provider}}"'
    changed_when: no
    tags: [ 'DatabaseService','configure' ]

  - name: set the BaseURL of the Robust instance
    ini_file:
      path: '{{ asset_config }}'
      section: Const
      option: BaseURL
      value: '"http:/{{ ansible_hostname}}"'
    changed_when: no
    tags: [ 'AssetService','configure' ]

  - name: configure location of gridadmin folder
    ini_file:
      path: '{{ asset_config }}'
      section: Const
      option: GridAdministratorFolder
      value: '"/home/{{admin_user}}/config-default"'
    changed_when: no
    tags: [ 'AssetService','configure' ]

  - name: set path to modular ini files
    ini_file:
      path: '{{ asset_config }}'
      section: Startup
      option: ConfigDirectory
      value: '"/home/{{admin_user}}/config-default/robust-include"'
    changed_when: no
    tags: [ 'AssetService','configure' ]

  - name: configure fsasset base directory
    ini_file:
      path: '{{ asset_config }}'
      section: AssetService
      option: BaseDirectory
      value: '"/home/{{ admin_user}}/fsassets/data"'
    changed_when: no
    tags: [ 'AssetService','configure' ]

  - name: configure fasasset spool directory
    ini_file:
      path: '{{ asset_config }}'
      section: AssetService
      option: SpoolDirectory
      value: '"/home/{{ admin_user}}/fsassets/tmp"'
    changed_when: no
    tags: [ 'AssetService','configure' ]
