---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:


    - name: Disk FreeSwitchVoice
      shell: >
          df / |
          awk '{print $5}'
      register: disk_free
      changed_when: false
      check_mode: false

    - name: System Information
      debug:
        msg: "{{ ansible_lsb.description }} : {{ ansible_processor[2] }}
        : CPU({{ ansible_processor_cores }})
        : MEM({{ ansible_memtotal_mb}})
        : DISK({{ disk_free.stdout_lines[1] }})"
 