---
# bring stack down

# restart mysql
- hosts: asset_database
  become: yes
  gather_facts : no
  tasks:
    - service: name=mysql state=restarted
      waitfor: port=3306 timeout=1

# bring stack up
